// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cabins": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve el listado completo de cabañas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cabañas"
                ],
                "summary": "Listar cabañas",
                "responses": {
                    "200": {
                        "description": "Lista de cabañas",
                        "schema": {
                            "$ref": "#/definitions/internal_cabins.CabinsListResponse"
                        }
                    },
                    "500": {
                        "description": "Error al obtener las cabañas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea una cabaña. Para anfitriones el id_anfitrion se toma del token; para administradores puede indicarse. Requiere token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cabañas"
                ],
                "summary": "Registrar cabaña",
                "parameters": [
                    {
                        "description": "Datos de la cabaña",
                        "name": "cabin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_cabins.CreateCabinRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Cabaña registrada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/internal_cabins.CreateCabinResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cabins/images/{cabinId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve todas las imágenes asociadas a la cabaña indicada.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Imágenes"
                ],
                "summary": "Listar imágenes de una cabaña",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de cabaña",
                        "name": "cabinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de imágenes",
                        "schema": {
                            "$ref": "#/definitions/internal_images.ImagesListResponse"
                        }
                    },
                    "400": {
                        "description": "ID de cabaña inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error al obtener imágenes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sube una imagen (JPEG, PNG o WebP, máx. 5 MB) asociada a una cabaña. Solo el dueño de la cabaña o un administrador.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Imágenes"
                ],
                "summary": "Subir imagen",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de cabaña",
                        "name": "cabinId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Archivo de imagen",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Imagen subida exitosamente",
                        "schema": {
                            "$ref": "#/definitions/internal_images.CreateImageResponse"
                        }
                    },
                    "400": {
                        "description": "Datos o formato inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Cabaña no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cabins/images/{cabinId}/principal": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve la imagen más reciente de la cabaña indicada. Requiere token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Imágenes"
                ],
                "summary": "Imagen principal de una cabaña",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de cabaña",
                        "name": "cabinId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Imagen principal",
                        "schema": {
                            "$ref": "#/definitions/internal_images.ImageResponse"
                        }
                    },
                    "400": {
                        "description": "ID de cabaña inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "La cabaña no tiene imágenes registradas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cabins/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Busca cabañas combinando filtros opcionales por nombre, anfitrión, capacidad y precio. Requiere token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cabañas"
                ],
                "summary": "Buscar cabañas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtro por nombre",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtro por ID de anfitrión",
                        "name": "host_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtro por nombre de anfitrión",
                        "name": "host_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Capacidad mínima",
                        "name": "min_capacity",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Capacidad máxima",
                        "name": "max_capacity",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Precio mínimo",
                        "name": "min_price",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Precio máximo",
                        "name": "max_price",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Resultados de la búsqueda",
                        "schema": {
                            "$ref": "#/definitions/internal_cabins.CabinCardsListResponse"
                        }
                    },
                    "400": {
                        "description": "Parámetros inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cabins/user/{userId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve las cabañas cuyo anfitrión es el usuario indicado. Solo el propio usuario o un administrador. Requiere token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cabañas"
                ],
                "summary": "Cabañas de un usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del anfitrión",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cabañas del usuario",
                        "schema": {
                            "$ref": "#/definitions/internal_cabins.CabinsListResponse"
                        }
                    },
                    "400": {
                        "description": "ID de usuario inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/cabins/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve los detalles de la cabaña indicada. Requiere token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cabañas"
                ],
                "summary": "Obtener cabaña por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de cabaña",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalle de la cabaña",
                        "schema": {
                            "$ref": "#/definitions/internal_cabins.CabinResponse"
                        }
                    },
                    "400": {
                        "description": "ID de cabaña inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Cabaña no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza los datos de una cabaña. Solo el dueño de la cabaña o un administrador. Requiere token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cabañas"
                ],
                "summary": "Actualizar cabaña",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de cabaña",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "cabin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_cabins.UpdateCabinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cabaña actualizada exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Cabaña no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina una cabaña. Solo el dueño de la cabaña o un administrador. Requiere token.",
                "tags": [
                    "Cabañas"
                ],
                "summary": "Eliminar cabaña",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de cabaña",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cabaña eliminada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/internal_cabins.DeleteCabinResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Cabaña no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/images/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve una imagen según su identificador. Requiere token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Imágenes"
                ],
                "summary": "Obtener imagen por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de imagen",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Imagen",
                        "schema": {
                            "$ref": "#/definitions/internal_images.ImageResponse"
                        }
                    },
                    "400": {
                        "description": "ID de imagen inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Imagen no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Elimina una imagen y su archivo físico. Solo el dueño de la cabaña o un administrador. Requiere token.",
                "tags": [
                    "Imágenes"
                ],
                "summary": "Eliminar imagen",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de imagen",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Imagen eliminada exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ID de imagen inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Imagen no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentica con correo y contraseña y devuelve un token Bearer. Endpoint público.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Iniciar sesión",
                "parameters": [
                    {
                        "description": "Credenciales de acceso",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_users.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuario autenticado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/internal_users.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Datos de entrada inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Correo o contraseña incorrectos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reservations": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea una reservación. Para clientes el usuario se toma del token; para administradores puede indicarse. Requiere token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservaciones"
                ],
                "summary": "Crear reservación",
                "parameters": [
                    {
                        "description": "Datos de la reservación",
                        "name": "reservation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_reservations.ReservationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Reservación registrada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/internal_reservations.CreateReservationResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Cabaña o usuario no existe",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflicto de fechas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reservations/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza la cabaña y las fechas de una reservación activa. Puede editar quien reservó, el dueño de la cabaña o un admin. Requiere token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservaciones"
                ],
                "summary": "Actualizar reservación",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de reservación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "reservation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_reservations.UpdateReservationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reservación actualizada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/internal_reservations.UpdateReservationResponse"
                        }
                    },
                    "400": {
                        "description": "Datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Reservación no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflicto de fechas o reservación no editable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/reservations/{id}/cancel": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Cancela una reservación activa. Puede cancelar quien reservó, el dueño de la cabaña o un admin, siempre que falten al menos 3 días para el inicio. Requiere token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservaciones"
                ],
                "summary": "Cancelar reservación",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de reservación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Reservación cancelada exitosamente",
                        "schema": {
                            "$ref": "#/definitions/internal_reservations.CancelReservationResponse"
                        }
                    },
                    "400": {
                        "description": "ID de reservación inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Reservación no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "No cancelable o con menos de 3 días de anticipación",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve todos los usuarios registrados. Requiere rol de administrador.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Listar usuarios",
                "responses": {
                    "200": {
                        "description": "Lista de usuarios",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_users.User"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos de administrador",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Error al obtener usuarios",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Crea una cuenta de usuario. Endpoint público, no requiere token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Registrar usuario",
                "parameters": [
                    {
                        "description": "Datos del usuario",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_users.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuario registrado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/internal_users.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Datos de entrada inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "El correo o DPI ya está registrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve el perfil de un usuario. Solo el propio usuario o un administrador. Requiere token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Obtener usuario por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Perfil del usuario",
                        "schema": {
                            "$ref": "#/definitions/internal_users.User"
                        }
                    },
                    "400": {
                        "description": "ID de usuario inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Usuario no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza los datos de perfil. Solo el propio usuario o un administrador. Requiere token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Usuarios"
                ],
                "summary": "Actualizar usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de usuario",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_users.UserUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuario actualizado exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Datos de entrada inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Sin permisos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Usuario no encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "El correo ya está registrado por otro usuario",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_cabins.CabinCardResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "host_id": {
                    "type": "integer"
                },
                "host_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "internal_cabins.CabinCardsListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_cabins.CabinCardResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_cabins.CabinResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "commission_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "host_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "rules": {
                    "type": "string"
                }
            }
        },
        "internal_cabins.CabinsListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_cabins.CabinResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_cabins.CreateCabinRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "commission_id": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "host_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "rules": {
                    "type": "string"
                }
            }
        },
        "internal_cabins.CreateCabinResponse": {
            "type": "object",
            "properties": {
                "cabin_id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_cabins.DeleteCabinResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "rows_affected": {
                    "type": "integer"
                }
            }
        },
        "internal_cabins.UpdateCabinRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "rules": {
                    "type": "string"
                }
            }
        },
        "internal_images.CreateImageResponse": {
            "type": "object",
            "properties": {
                "image_id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "internal_images.ImageResponse": {
            "type": "object",
            "properties": {
                "cabin_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_images.ImagesListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_images.ImageResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_reservations.CancelReservationResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "reservation": {
                    "$ref": "#/definitions/internal_reservations.ReservationDetail"
                }
            }
        },
        "internal_reservations.CreateReservationResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "reservation_id": {
                    "type": "integer"
                }
            }
        },
        "internal_reservations.ReservationDetail": {
            "type": "object",
            "properties": {
                "cabin_id": {
                    "type": "integer"
                },
                "cancelled_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "host_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_reservations.ReservationRequest": {
            "type": "object",
            "properties": {
                "cabin_id": {
                    "type": "integer"
                },
                "end_date": {
                    "description": "Formato AAAA-MM-DD",
                    "type": "string"
                },
                "start_date": {
                    "description": "Formato AAAA-MM-DD",
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_reservations.UpdateReservationRequest": {
            "type": "object",
            "properties": {
                "cabin_id": {
                    "type": "integer"
                },
                "end_date": {
                    "description": "Formato AAAA-MM-DD",
                    "type": "string"
                },
                "start_date": {
                    "description": "Formato AAAA-MM-DD",
                    "type": "string"
                }
            }
        },
        "internal_reservations.UpdateReservationResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "reservation": {
                    "$ref": "#/definitions/internal_reservations.ReservationDetail"
                }
            }
        },
        "internal_users.RegisterRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "dpi": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_users.RegisterResponse": {
            "type": "object",
            "properties": {
                "mensaje": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "internal_users.User": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "dpi": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_role": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "internal_users.UserLoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_users.UserLoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_users.UserUpdate": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Token JWT obtenido en el endpoint login. Enviar como: Bearer \u003ctoken\u003e",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/cdv-api",
	Schemes:          []string{},
	Title:            "Casa Del Valle API",
	Description:      "Documentación de los endpoints de la API de Casa Del Valle.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
