# --- Etapa de build ---
FROM public.ecr.aws/docker/library/node:24-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build -- --configuration production

# --- Etapa final (nginx sirviendo estáticos) ---
FROM public.ecr.aws/docker/library/nginx:1.27-alpine

COPY --from=builder /app/dist/Casa-Del-Valle-FE/browser /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80